version: '3'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.5.4"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      cluster.name: paris
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.5.4"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  fluentd:
    image: "custom-fluentd:1.3.3-c1"
    network_mode: host
    command:
      - "-v"
    healthcheck:
      test: ["CMD-SHELL", "netstat -antp | grep LISTEN | grep \"0.0.0.0:24224\""]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - 3000:3000
    environment:
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_SECURITY_ADMIN_PASSWORD: secret
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
    depends_on:
      - elasticsearch

