version: '3'

services:
  consul-server:
    image: "consul:1.4.0"
    command:
      - agent
      - "-client"
      - "0.0.0.0"
      - "-server"
      - "-bind"
      - "0.0.0.0"
      - "-bootstrap-expect"
      - "1"
      - "-ui"
    ports:
      - 8500:8500
    environment:
      CONSUL_LOCAL_CONFIG: '{"datacenter":"paris","server":true,"enable_debug":true}'

  traefik:
    image: "traefik:1.7.7-alpine"
    ports:
      - 9000:80
      - 9001:8080
    volumes:
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
    depends_on:
      - "consul-server"

  red:
    image: "color:1.0.0"
    ports:
      - 8001:8000
    environment:
      CONSUL_HOSTNAME: "consul-server"
    stop_grace_period: 6s
    depends_on:
      - "consul-server"
      - "traefik"

  black:
    image: "color:1.0.0"
    ports:
      - 8002:8000
    command:
      - "--color=black"
    environment:
      CONSUL_HOSTNAME: "consul-server"
    stop_grace_period: 6s
    depends_on:
      - "consul-server"
      - "traefik"

