apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "example.carnage.sh/v1alpha1",
          "kind": "Bot",
          "metadata": {
            "name": "example-bot"
          },
          "spec": {
            "alias": "mybot"
          }
        }
      ]
    capabilities: Basic Install
  name: simple-op.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Bot is the Schema for the bots API
      kind: Bot
      name: bots.example.carnage.sh
      version: v1alpha1
      displayName: Simple Op
  description: Placeholder description
  displayName: Simple Op
  install:
    spec:
      deployments:
      - name: simple-op
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: simple-op
          strategy: {}
          template:
            metadata:
              labels:
                name: simple-op
            spec:
              containers:
              - command:
                - simple-op
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: simple-op
                image: quay.io/carnage/bot-operator:v0.0.1
                imagePullPolicy: Always
                name: simple-op
                resources: {}
              serviceAccountName: simple-op
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - simple-op
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - example.carnage.sh
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: simple-op
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operators
  maintainers:
  - email: tryme@gmail.com
    name: Gregory
  maturity: alpha
  provider:
    name: Gregory
  version: 0.0.1
