apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cloud-for-fun
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/carnage-sh/cloud-for-fun
