---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helloworld
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  namespace: default
spec:
  containers:
  - image: debian:9.7
    name: helloworld
    command:
      - /bin/bash
      - "-c"
      - "sleep 1000"
  serviceAccountName: helloworld
...
