apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: kevent
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          labels:
            app: kevent
        spec:
          serviceAccountName: knative-sa
          container:
            image: 184975490479.dkr.ecr.eu-west-1.amazonaws.com/kevent:0.0.3

