version: '3'

services:
  simpleapi:
    image: simpleapi:1.0.0
    ports:
      - 8080:8080
    networks:
      - backend

  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend

networks:
  backend:
