version: '3'

services:
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.13.0
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    ports:
      - 9115:9115
    command:
      - "--config.file=/config/blackbox.yml"
      - "--log.level=debug"

  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml

  alertmanager:
    image: prom/alertmanager:v0.16.1
    volumes:
      - ./alertmanager.slack:/etc/alertmanager/alertmanager.yml
      - ./cloud-for-fun.tpl:/etc/alertmanager/templates/cloud-for-fun.tpl
    ports:
        - 9093:9093
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"

  nginx:
    image: nginx:1.15.8-alpine

