version: '3'

services:
  gaming:
    image: gaming:1.0.0
    ports:
      - 8080:8080
    environment:
      REDIS_URL: "redis://redis:6379"

  redis:
    image: redis:5.0.2
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data

  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - 3000:3000
    environment:
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_SECURITY_ADMIN_PASSWORD: secret
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./configuration/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./configuration/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
