---
apiVersion: v1
kind: Namespace
metadata:
  name: ops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-helper
  namespace: ops
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-helper
  namespace: default
rules:
- apiGroups: [""] 
  resources: 
  - secrets
  - serviceaccounts
  verbs: 
  - get
  - list
  - delete
  - create
  - update
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-helper
  namespace: default
subjects:
- kind: User
  name: system:serviceaccount:ops:ecr-helper
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ecr-helper
  apiGroup: rbac.authorization.k8s.io
---
