{
 "title": "Logme",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Log Activity (logme)",
   "type": "graph",
   "description": "Content of the logs from the logme container",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "INFO",
     "bucketAggs": [
      {
       "fake": true,
       "field": "logtime",
       "id": "5",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "loglevel:INFO",
     "timeField": "logtime"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "logtime", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "loglevel:WARN",
     "timeField": "logtime"
    }
   ]
  },
  {
   "title": "# Containers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "logme",
     "bucketAggs": [
      { "field": "logtime", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "shortid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "container_name:logme",
     "timeField": "logtime"
    }
   ]
  },
  {
   "title": "Message (WARN)",
   "type": "table",
   "description": "List of messages when loglevel=WARB",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "Warning",
     "metrics": [
      {
       "field": "select metric",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "loglevel:WARN",
     "timeField": "logtime"
    }
   ]
  }
 ]
}