apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.12
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /tmp/config
      volumes:
      - name: nginx-config
        configMap:
          name: nginx
