global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: app-service
    consul_sd_configs:
      - server: 'consul-server:8500'
        datacenter: paris
        services:
          - color

    relabel_configs:
      - source_labels: ['__meta_consul_service']
        regex:         '(.*)'
        target_label:  'api'
        replacement:   '$1'

rule_files:
  - /etc/prometheus/prometheus.rules.yml

