groups:
  - name: metrics_by_api
    rules:
      - record: service_total
        expr: sum by (api)(up)

  - name: monitoring
    rules:
      - alert: NotEnoughService
        expr: |
          (sum by (api)(up)
            or absent(up{api="color"})-1
            or absent(up{api="lb"})-1
          ) < 2
        labels:
          severity: red
        annotations:
          summary: "The number of deployed services should be at least 2"

