groups:
  - name: metrics_by_api
    rules:
      - record: service_total
        expr: sum(up) by (api)

  - name: monitoring
    rules:
      - alert: NotEnoughColorService
        expr: sum(up{api="color"}) <= 1
        labels:
          severity: red
        annotations:
          summary: "The number of color services should be at least 2"

